### ISSUE TITLE
😂🤣😂

### ISSUE THREAD

**Issue by danny-andrews** [mat3e/brains#1]
Thanks for this. So much.

That is all. Feel free to close. :)

**Comment by mat3e** [comment]
This is the kind of an issue, I can see all the time :D

Feel free to star the project and to contribute (e.g. font options, like size and family, can be added) :)

**Comment by danny-andrews** [comment]
> Feel free to star the project and to contribute

Cool! I might give a crack at text wrapping if I find the time.

p.s. https://medium.com/@lunde.andrews/easing-into-functional-programming-in-javascript-30056bcc49a9 (scroll to the bottom).
